socavon_web/Models/ErrorViewModel.cs
using System;

namespace socavon_web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

socavon_web/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace socavon_web.Models
{
    public class User
    {
        
    }
}

socavon_web/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace socavon_web.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "El correo es un campo obligatorio")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "La clave es un campo obligatorio")]
        public string Clave { get; set; }
    }
}

socavon_web/ViewModels/LogupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace socavon_web.ViewModels
{
    public class LogupViewModel
    {
        [Required(ErrorMessage = "El nombre es un campo requerido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El apellido es un campo requerido")]
        public string Apellido { get; set; }

        [Required(ErrorMessage = "El correo es un campo requerido")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "La clave es un campo requerido")]
        public string Clave { get; set; }

        [Required(ErrorMessage = "La clave es un campo requerido")]
        public string ClaveVerificada { get; set; }

    }
}

socavon_web/ViewModels/TareaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace socavon_web.ViewModels
{
    public class TareaViewModel
    {

        [Required(ErrorMessage = "El título es un campo requerido")]
        public string Title { get; set; }

        public string Description { get; set; }

        [Required(ErrorMessage = "La prioridad es un campo requerido")]
        public string Priority { get; set; }


    }
}

socavon_web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using socavon_web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace socavon_web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

socavon_web/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using socavon_web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace socavon_web.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LogIn(LoginViewModel User)
        {
            if (!ModelState.IsValid){
                return View();
            }
            return Redirect("");
        }

        public IActionResult LogUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LogUp(LogupViewModel userlogup)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            return RedirectToAction("Index");
        }
    }


}

socavon_web/Controllers/TareaController.cs
using Microsoft.AspNetCore.Mvc;
using socavon_web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace socavon_web.Controllers
{
    public class TareaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Nueva()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Nueva(TareaViewModel nuevaTarea)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Modificar()
        {
            return View();
        }

        public IActionResult Borrar()
        {
            return View();
        }
    }
}

socavon_web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Para empezar a usar la app, por favor inicie sesión:</p>
    <a class="btn btn-lg btn-primary" asp-action="Index"  asp-controller="Login"> Iniciar Sesión </a>
</div>

socavon_web/Views/Login/Index.cshtml
@model socavon_web.ViewModels.LoginViewModel

<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h2>Completa el formulario</h2>
            <form asp-controller="Login" asp-action="Login" method="post">
                <div class="form-group">
                    <label asp-for="Correo"></label>
                    <input id="correo" name="correo" type="text" placeholder="correo@ejemplo.com" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Clave"></label>
                    <input id="clave" name="clave" type="password" placeholder="0000000000" class="form-control" />
                </div>
                <div class="form-group">
                    <input value="Ingresar" type="submit" class="btn btn-block btn-dark" />
                </div>
            </form>
            <p>¿Todavía no tenes cuenta? <a asp-action="Logup" asp-controller="Login">Registrate</a></p>
        </div>
    </div>
</div>

socavon_web/Views/Login/LogUp.cshtml
@model socavon_web.ViewModels.LogupViewModel


<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h2>Completa el formulario</h2>
            <form asp-controller="Login" asp-action="Logup" method="post">
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" type="text" placeholder="Usuario" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Apellido" class="control-label"></label>
                    <input asp-for="Apellido" type="text" placeholder="Usuario" class="form-control" />
                    <span asp-validation-for="Apellido" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Correo" class="control-label"></label>
                    <input asp-for="Correo" type="text" placeholder="correo@ejemplo.com" class="form-control" />
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Clave" class="control-label"></label>
                    <input asp-for="Clave" type="password" placeholder="0000000000" class="form-control" />
                    <span asp-validation-for="Clave" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClaveVerificada" class="control-label"></label>
                    <input asp-for="ClaveVerificada" type="password" placeholder="0000000000" class="form-control" />
                    <span asp-validation-for="ClaveVerificada" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input value="Registarse" type="submit" class="btn btn-block btn-info" />
                </div>
            </form>
        </div>
    </div>
</div>


@section scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
 }

socavon_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Listado de Tareas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Listador</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarea" asp-action="Index">Tareas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Listador - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

socavon_web/Views/Tarea/Index.cshtml
<div class="container">
    <div class="row">
        <h2>Gracias por elegirnos "nombreusuario"</h2>
    </div>
    <div class="row">
        <div class="item col-md-6">
            <h3>Tareas Pendientes</h3>
        </div>
        <div class="item col-md-6">
            <a asp-action="Nueva" asp-controller="Tarea" class="btn btn-primary btn-block">Agregar Nueva Tarea</a>
        </div>
    </div>
    
</div>

socavon_web/Views/Tarea/Nueva.cshtml
@model socavon_web.ViewModels.TareaViewModel


<div class="container">
    <div class="row">
        <h2>Ingresar una nueva tarea.</h2>
    </div>

    <form asp-action="Nueva" asp-controller="Tarea" method="post">
        <div class="form-group">
            <label asp-for="Title">Titulo</label>
            <input asp-for="Title" class="form-control" type="text" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Descripción</label>
            <input asp-for="Description" class="form-control" type="text" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Prioridad</label>
            <select class="form-select" asp-for="Priority">
                <option selected value="baja">Baja</option>
                <option value="media">Media</option>
                <option value="alta">Alta</option>
            </select>
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Crear Nueva Tarea</button>
        </div>
    </form>
</div>

@section scripts{ 
 @{ <partial name="_ValidationScriptsPartial" /> }
}